AWSTemplateFormatVersion: "2010-09-09"
Description: Static site on S3 + CloudFront with Route53

Parameters:
  SiteDomain:
    Type: String
    Description: Apex domain, e.g. example.com
  WwwDomain:
    Type: String
    Description: WWW domain, e.g. www.example.com
  HostedZoneId:
    Type: String
    Description: Route53 hosted zone ID for the apex domain
  AcmCertArn:
    Type: String
    Description: ACM cert ARN in us-east-1 for CloudFront

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SiteDomain
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${SiteDomain}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  SiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref SiteDomain
          - !Ref WwwDomain
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt SiteBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref OriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt WwwRedirectFunction.FunctionMetadata.FunctionARN

  WwwRedirectFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "${SiteDomain}-www-redirect"
      AutoPublish: true
      FunctionConfig:
        Comment: Redirect www to apex
        Runtime: cloudfront-js-1.0
      FunctionCode: |
        function handler(event) {
          var request = event.request;
          var host = request.headers.host.value;
          if (host === "${WwwDomain}") {
            return {
              statusCode: 301,
              statusDescription: "Moved Permanently",
              headers: {
                location: { value: "https://${SiteDomain}" + request.uri }
              }
            };
          }
          return request;
        }

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${SiteBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${SiteDistribution}"

  ApexRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref SiteDomain
      Type: A
      AliasTarget:
        DNSName: !GetAtt SiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  ApexRecordAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref SiteDomain
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt SiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  WwwRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref WwwDomain
      Type: A
      AliasTarget:
        DNSName: !GetAtt SiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  WwwRecordAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref WwwDomain
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt SiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  BucketName:
    Value: !Ref SiteBucket
  DistributionId:
    Value: !Ref SiteDistribution
  DistributionDomain:
    Value: !GetAtt SiteDistribution.DomainName
